name: food_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_multi_formatter: ^2.13.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/avatar_placeholder.png
    - assets/images/restaurant_1.jpg
    - assets/images/restaurant_2.jpg
    - assets/images/restaurant_3.jpg
    - assets/images/steak.jpg
    - assets/images/caesar.jpg
    - assets/images/philadelphia.jpg
    - assets/images/salmon_sushi.jpg
    - assets/images/margherita.jpg
    - assets/images/pepperoni.jpg
    - assets/images/hawaiian_chicken.jpg
    - assets/images/greek_salad.jpg

  uses-material-design: true
